// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: apps/shared/proto/grader.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId  string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`       // UUID ของ submission
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`                                   // "cpp", "python", "go"
	SourceCode    string                 `protobuf:"bytes,3,opt,name=source_code,json=sourceCode,proto3" json:"source_code,omitempty"`             // โค้ดนักเรียน
	Stdin         string                 `protobuf:"bytes,4,opt,name=stdin,proto3" json:"stdin,omitempty"`                                         // Input ของ testcase
	TimeoutMs     int64                  `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`               // เวลาสูงสุด (ms)
	MemoryLimitMb int64                  `protobuf:"varint,6,opt,name=memory_limit_mb,json=memoryLimitMb,proto3" json:"memory_limit_mb,omitempty"` // แรมสูงสุด (MB)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeRequest) Reset() {
	*x = GradeRequest{}
	mi := &file_apps_shared_proto_grader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeRequest) ProtoMessage() {}

func (x *GradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_shared_proto_grader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeRequest.ProtoReflect.Descriptor instead.
func (*GradeRequest) Descriptor() ([]byte, []int) {
	return file_apps_shared_proto_grader_proto_rawDescGZIP(), []int{0}
}

func (x *GradeRequest) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *GradeRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *GradeRequest) GetSourceCode() string {
	if x != nil {
		return x.SourceCode
	}
	return ""
}

func (x *GradeRequest) GetStdin() string {
	if x != nil {
		return x.Stdin
	}
	return ""
}

func (x *GradeRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *GradeRequest) GetMemoryLimitMb() int64 {
	if x != nil {
		return x.MemoryLimitMb
	}
	return 0
}

type GradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId  string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	IsTle         bool                   `protobuf:"varint,2,opt,name=is_tle,json=isTle,proto3" json:"is_tle,omitempty"` // Time Limit Exceeded
	IsMle         bool                   `protobuf:"varint,3,opt,name=is_mle,json=isMle,proto3" json:"is_mle,omitempty"` // Memory Limit Exceeded
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,5,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,6,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeResponse) Reset() {
	*x = GradeResponse{}
	mi := &file_apps_shared_proto_grader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeResponse) ProtoMessage() {}

func (x *GradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_shared_proto_grader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeResponse.ProtoReflect.Descriptor instead.
func (*GradeResponse) Descriptor() ([]byte, []int) {
	return file_apps_shared_proto_grader_proto_rawDescGZIP(), []int{1}
}

func (x *GradeResponse) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *GradeResponse) GetIsTle() bool {
	if x != nil {
		return x.IsTle
	}
	return false
}

func (x *GradeResponse) GetIsMle() bool {
	if x != nil {
		return x.IsMle
	}
	return false
}

func (x *GradeResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *GradeResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *GradeResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

var File_apps_shared_proto_grader_proto protoreflect.FileDescriptor

const file_apps_shared_proto_grader_proto_rawDesc = "" +
	"\n" +
	"\x1eapps/shared/proto/grader.proto\x12\x06grader\"\xcd\x01\n" +
	"\fGradeRequest\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x1f\n" +
	"\vsource_code\x18\x03 \x01(\tR\n" +
	"sourceCode\x12\x14\n" +
	"\x05stdin\x18\x04 \x01(\tR\x05stdin\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\x03R\ttimeoutMs\x12&\n" +
	"\x0fmemory_limit_mb\x18\x06 \x01(\x03R\rmemoryLimitMb\"\xaf\x01\n" +
	"\rGradeResponse\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12\x15\n" +
	"\x06is_tle\x18\x02 \x01(\bR\x05isTle\x12\x15\n" +
	"\x06is_mle\x18\x03 \x01(\bR\x05isMle\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x05 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x06 \x01(\tR\x06stderr2E\n" +
	"\rGraderService\x124\n" +
	"\x05Grade\x12\x14.grader.GradeRequest\x1a\x15.grader.GradeResponseB7Z5github.com/KPV2004/gradient-backend/apps/shared/protob\x06proto3"

var (
	file_apps_shared_proto_grader_proto_rawDescOnce sync.Once
	file_apps_shared_proto_grader_proto_rawDescData []byte
)

func file_apps_shared_proto_grader_proto_rawDescGZIP() []byte {
	file_apps_shared_proto_grader_proto_rawDescOnce.Do(func() {
		file_apps_shared_proto_grader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_shared_proto_grader_proto_rawDesc), len(file_apps_shared_proto_grader_proto_rawDesc)))
	})
	return file_apps_shared_proto_grader_proto_rawDescData
}

var file_apps_shared_proto_grader_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_apps_shared_proto_grader_proto_goTypes = []any{
	(*GradeRequest)(nil),  // 0: grader.GradeRequest
	(*GradeResponse)(nil), // 1: grader.GradeResponse
}
var file_apps_shared_proto_grader_proto_depIdxs = []int32{
	0, // 0: grader.GraderService.Grade:input_type -> grader.GradeRequest
	1, // 1: grader.GraderService.Grade:output_type -> grader.GradeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apps_shared_proto_grader_proto_init() }
func file_apps_shared_proto_grader_proto_init() {
	if File_apps_shared_proto_grader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_shared_proto_grader_proto_rawDesc), len(file_apps_shared_proto_grader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_shared_proto_grader_proto_goTypes,
		DependencyIndexes: file_apps_shared_proto_grader_proto_depIdxs,
		MessageInfos:      file_apps_shared_proto_grader_proto_msgTypes,
	}.Build()
	File_apps_shared_proto_grader_proto = out.File
	file_apps_shared_proto_grader_proto_goTypes = nil
	file_apps_shared_proto_grader_proto_depIdxs = nil
}
